GET http://localhost:5000/


### add data
POST http://localhost:5000/animal/
Content-Type: application/json

{
    "name": "katt",
    "dangerous": "no",
    "fur": "long"
}

### get all stored data
GET http://localhost:5000/animals/


### get specific item from db (Since ID is randomized, get ID fron stored data and replace "?")
GET http://localhost:5000/animal/?/

### get specific item from db (404, does not exist)
GET http://localhost:5000/animal/666/

### edit specific item from db (Since ID is randomized, get ID fron stored data and replace "?")
PUT http://localhost:5000/animal/?/
Content-Type: application/json

{
    "name": "orm",
    "dangerous": "yes",
    "fur": "no"
}

### delete specific item from db (Since ID is randomized, get ID fron stored data and replace "?")
DELETE http://localhost:5000/animal/?/

### delete item from db (404 Bad request - does not exist)
DELETE http://localhost:5000/animal/666/

